// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Auth struct {
	ID        string
	UserID    string
	Token     string
	UserAgent sql.NullString
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Category struct {
	ID    string
	Name  string
	Color string
}

type Task struct {
	ID          string
	Title       string
	Description string
	Status      string
	PriorityID  sql.NullString
	DueDate     sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      string
}

type TaskCategory struct {
	TaskID     string
	CategoryID string
}

type TaskPriority struct {
	ID        string
	Name      string
	Level     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID         string
	Username   string
	Password   string
	Email      string
	PrivateKey string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
